export const AUTH_SUCCESS = 'AUTH/AUTH_SUCCESS';
export const FETCHING_IMAGES = 'GALLERY/FETCHING_IMAGES';
export const FETCHING_IMAGES_COMPLETED = 'GALLERY/FETCHING_IMAGES_COMPLETED';
export const FETCHING_IMAGES_ERROR = 'GALLERY/FETCHING_IMAGES_ERROR';
