export const AUTH_SUCCESS = 'AUTH/AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH/AUTH_FAILURE';

export const SET_NEXT_PAGE = 'GALLERY/SET_NEXT_PAGE';
export const FETCHING_IMAGES = 'GALLERY/FETCHING_IMAGES';
export const FETCHING_IMAGES_COMPLETED = 'GALLERY/FETCHING_IMAGES_COMPLETED';
export const FETCHING_IMAGES_ERROR = 'GALLERY/FETCHING_IMAGES_ERROR';
export const TOGGLE_PHOTO_LIKE = 'GALLERY/TOGGLE_PHOTO_LIKE';

export const FETCHING_PHOTO = 'IMAGEVIEW/FETCHING_PHOTO';
export const FETCHING_PHOTO_COMPLETED = 'IMAGEVIEW/FETCHING_FETCHING_PHOTO_COMPLETED';
export const FETCHING_PHOTO_ERROR = 'IMAGEVIEW/FETCHING_PHOTO_ERROR';

export const RESET_PHOTO_HAS_LOADED = 'IMAGEVIEW/RESET_PHOTO_HAS_LOADED';


